- name: test
  hosts: all
  gather_facts: false
  become: true
  vars:
    manala_proxmox_instances_defaults:
        api_user: root@pam
        api_password: proxmox-api-password
        api_host: hv-1
        node: hv-1
        password: root-password
    manala_proxmox_instances:
      - vmid: 804
        hostname: mysql-1.local
        cpus: 2
        memory: 2048
        swap: 512
        disk: 30
        netif: '{
          "net0": "name=eth0,ip=192.168.0.1/24,gw=192.168.0.254,bridge=vmbr1"
        }'
        pool: db
        ostemplate: local:vztmpl/debian-8.0-manala_2.0.0_amd64.tar.gz	
  roles:
    - manala.proxmox
